name: "modbus-proxy2"
description: "Proxy for Accessing modbus systems. Allows multiple client connections"
version: "1.0.0"
slug: "modbus_proxy2"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
url: "https://github.com/Infernoken76/ha-modbusproxy1"
startup: services
init: false
options:
  upstreamhost: "192.168.1.80"
  upstreamport: 502
  listenport: 503
  connection_time: 2
  timeout: 10
  loglevel: "DEBUG"
schema:
  upstreamhost: str
  upstreamport: int
  listenport: int
  connection_time: float
  timeout: int
  loglevel: list(INFO|DEBUG|ERROR)
ports:
  503/tcp: 503
